AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31 # To use SAM for less verbose CF

Description: 
  Setting up web hosting for a static frontend, served with cloudfront.

Parameters:
  EnvironmentName:
    Type: String
    Default: env-name
    Description: "Environment prefixing resources, tagging resources and for importing resources from other stacks"

Resources: 
  s3Bucket: # To host static web assets
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: !Sub ${EnvironmentName}-web-hosting
      Tags:
        - Key: project
          Value: !Sub ${EnvironmentName}

  CloudFrontOriginAccessIdentity: # Identity to allow cloudFront to access our private bucket.
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref s3Bucket

  s3BucketPolicy: # Bucket policy that allows the aboe OAI to access the buvket.
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref s3Bucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref s3Bucket
                  - '/*'
            Principal: 
              AWS: !Join
                - ''
                - - 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity '
                  - !Ref CloudFrontOriginAccessIdentity


  cloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        # Aliases:
        #   - CNAME you own
        DefaultCacheBehavior: 
          AllowedMethods: # Which methods to forward to S3
            - GET
            - HEAD
            - OPTIONS
          CachedMethods: # Which methods to cache responses for at cloudfront
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          DefaultTTL: 60 # in seconds
          MaxTTL: 240 # in seconds
          MinTTL: 60 # in seconds
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          TargetOriginId: s3origin # Unsure what this does, but required property
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        PriceClass: PriceClass_All
        Origins:
          - DomainName: !GetAtt s3Bucket.RegionalDomainName
            Id: s3origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}
        IPV6Enabled: false
        ViewerCertificate: 
          CloudFrontDefaultCertificate: true
          # AcmCertificateArn: arn:aws:acm:us-east-1:accountID:certificate/xxxxx
          # MinimumProtocolVersion: TLSv1
          # SslSupportMethod: sni-only
      Tags:
        - Key: project
          Value: !Sub ${EnvironmentName}


Outputs:
  Domain:
    Description: Cloudfront Domain
    Value: !GetAtt cloudfrontDistribution.DomainName
  s3Bucket:
    Description: S3 Bucket Name hosting the static website
    Value: !Ref s3Bucket
    Export:
      Name: !Sub ${EnvironmentName}:webhosting:bucket