export const SET_GAME = "SET_GAME";
export const WORD_CLICK = "WORD_CLICK";
export const SET_SCORE = "SET_SCORE";
export const INCREMENT_SONG_INDEX = "INCREMENT_SONG_INDEX";
export const DECREMENT_SONG_INDEX = "DECREMENT_SONG_INDEX";
export const REVEAL_ARTIST = "REVEAL_ARTIST";
